### ISSUE TITLE
Incorrect Info in dashboard

### ISSUE THREAD

**Issue by superboyiii** [neoburger/dashboard#3]
NhAhgt6bVrFBhuQSN1xH9D923gUytyE1aJ
![1632380364(1)](https://user-images.githubusercontent.com/38493437/134466269-088c3b3d-be57-44e8-bc06-175c3de90bc8.png)
https://neo3.neotube.io/address/NhAhgt6bVrFBhuQSN1xH9D923gUytyE1aJ
![1632380495(1)](https://user-images.githubusercontent.com/38493437/134466410-7dd87114-37ac-48c0-8b14-d9874aa8a534.png)

**Comment by vang1ong7ang** [comment]
thanks for reporting such problems.

i think it is currently fixed through #5
